title:             Cheng Blog
email:             chengchengeasy@gmail.com
description:       Interesting
author:            CC
baseurl:           ""
url:               "http://chengchengeasy.github.io"

# Social Profiles
twitter_username:  MacgradyTracy
github_username:   chengchengeasy
# facebook_username: FengCheng

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
